### PR TITLE
Fix typescript-eslint

### PR DESCRIPTION
**Pull request by jakebailey**
This has been failing since the start; our auto-install system gets confused by the dummypkg and tries to install it, even though it's not a part of ts-eslint's monorepo and that makes yarn sad.

```
Starting #2 / 6: https://github.com/typescript-eslint/typescript-eslint.git
/mnt/vss/_work/1/s> sudo mount -t tmpfs -o size=4g tmpfs /mnt/ts_downloads
Cloning if absent
Cloning https://github.com/typescript-eslint/typescript-eslint.git into typescript-eslint
Installing packages if absent
/mnt/ts_downloads/typescript-eslint> yarn cache clean --all
➤ YN0000: Done in 0s 109ms

Error installing packages for typescript-eslint:
> Error: Failed to install packages for tools/dummypkg:
> Exited with code 1
> Usage Error: The nearest package directory (/mnt/ts_downloads/typescript-eslint/tools/dummypkg) doesn't seem to be part of the project declared in /mnt/ts_downloads/typescript-eslint.
> 
> - If /mnt/ts_downloads/typescript-eslint isn't intended to be a project, remove any yarn.lock and/or package.json file there.
> - If /mnt/ts_downloads/typescript-eslint is intended to be a project, it might be that you forgot to list tools/dummypkg in its workspace configuration.
> - Finally, if /mnt/ts_downloads/typescript-eslint is fine and you intend tools/dummypkg to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.
> 
> $ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
> No stderr
>     at installPackages (/mnt/vss/_work/1/s/dist/main.js:666:27)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async installPackagesAndGetCommands (/mnt/vss/_work/1/s/dist/main.js:69:9)
>     at async getTscRepoResult (/mnt/vss/_work/1/s/dist/main.js:338:31)
>     at async mainAsync (/mnt/vss/_work/1/s/dist/main.js:523:19)
Repo https://github.com/typescript-eslint/typescript-eslint.git had status "Package install failed"
Cleaning up repo
```

Instead, move it over to a script, like we do vscode, prettier, pyright.

This fails but for a better reason:

```
+ yarn build

 NX   Nx Cloud Manually Disabled

Nx will continue running, but nothing will be written or read from the remote cache.
Run details will also not be available in the Nx Cloud UI.

If this wasn't intentional, check for the NX_NO_CLOUD environment variable, the --no-cloud flag


 NX   Running target build for 13 projects and 1 task they depend on:

- rule-schema-to-typescript-types
- eslint-plugin-internal
- typescript-eslint
- typescript-estree
- eslint-plugin
- scope-manager
- visitor-keys
- rule-tester
- type-utils
- ast-spec
- parser
- types
- utils



> nx run ast-spec:build  [existing outputs match the cache, left as is]


api-extractor 7.38.0  - https://api-extractor.com/

Using configuration from ./api-extractor.json
Analysis will use the bundled TypeScript version 5.5.0-dev

API Extractor completed successfully

> nx run types:copy-ast-spec  [existing outputs match the cache, left as is]

src/generated/ast-spec.ts 286ms
Copied ast-spec.ts

> nx run types:build  [existing outputs match the cache, left as is]


> nx run visitor-keys:build  [existing outputs match the cache, left as is]


> nx run typescript-estree:build

src/ts-estree/ts-nodes.ts(189,8): error TS2694: Namespace 'ts' has no exported member 'InputFiles'.
src/ts-estree/ts-nodes.ts(191,8): error TS2694: Namespace 'ts' has no exported member 'UnparsedSource'.
src/convert.ts(264,31): error TS2345: Argument of type 'Omit<TSESTreeToTSNode<T>, "parent">' is not assignable to parameter of type 'Pick<Node, "getEnd" | "getStart">'.
  Type 'Omit<TSESTreeToTSNode<T>, "parent">' is missing the following properties from type 'Pick<Node, "getEnd" | "getStart">': getEnd, getStart
src/convert.ts(845,45): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(857,43): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(997,63): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(1011,54): error TS7006: Parameter 'declaration' implicitly has an 'any' type.
src/convert.ts(1011,67): error TS7006: Parameter 'i' implicitly has an 'any' type.
src/convert.ts(1041,47): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(1047,38): error TS7006: Parameter 'declaration' implicitly has an 'any' type.
src/convert.ts(1047,51): error TS7006: Parameter 'i' implicitly has an 'any' type.
src/convert.ts(1085,41): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(1092,39): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(1103,45): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(1317,47): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(1469,39): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(1483,41): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(1611,36): error TS7006: Parameter 'templateSpan' implicitly has an 'any' type.
src/convert.ts(1827,24): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(1913,64): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(1956,60): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(2182,41): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(2223,38): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(2368,39): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(2376,39): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(2399,60): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(2427,58): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(2575,37): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(2697,43): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(2815,36): error TS7006: Parameter 'member' implicitly has an 'any' type.
src/convert.ts(2893,37): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(3041,33): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(3047,33): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(3118,48): error TS7006: Parameter 'el' implicitly has an 'any' type.
src/convert.ts(3166,36): error TS7006: Parameter 'templateSpan' implicitly has an 'any' type.
src/convert.ts(604,7): error TS2578: Unused '@ts-expect-error' directive.



 NX   Running target build for 13 projects and 1 task they depend on failed

Tasks not run because their dependencies failed or --nx-bail=true:

- rule-schema-to-typescript-types:build
- eslint-plugin-internal:build
- typescript-eslint:build
- eslint-plugin:build
- scope-manager:build
- rule-tester:build
- type-utils:build
- parser:build
- utils:build

Failed tasks:

- typescript-estree:build
```

i.e. that we removed a bunch of deprecated junk.

### CODE REVIEW

**Comment by jakebailey** [comment]
I'm still not super happy with this, since the build completely stops due to the first error from the fact that it needs TS itself to create files for itself and that means that we can stop getting good errors for ts-eslint.

**Comment by jakebailey** [comment]
@JoshuaKGoldberg Do you have any ideas for a way to typecheck without actually linking TypeScript into the repo? I don't think we want to be testing the AST node importing script bit, just whether or not your code compiles, but since you don't use project references and instead use some nx stuff, I have no idea how it should actually be checked.

**Comment by JoshuaKGoldberg** [comment]
cc @bradzacher @JamesHenry - it's an interesting ask that I don't know we've looked at before. Whenever I need to skip Nx caching I usually run `yarn build --skip-nx-cache`, as I don't have `nx` or any similar commands installed globally locally.

In theory I suppose you could run `yarn build` in each of the packages in order of their dependencies? I could have sworn I used to have a tool to do this, but can't find it...

**Comment by jakebailey** [comment]
Technically speaking, the original problem could be solved if the dummpypkg were listed in the workspaces prop in package.json; the heuristic tries to install it but yarn fails. Then our infra would be able to find all of the tsconfigs in the repo and run them via a heuristic.

Otherwise, I can use this manual script and then go into each one and run tsc, but it's hard when you don't want to hardcode the order, but the repo itself uses another tool such that I can't really use what's built-in.

**Comment by JoshuaKGoldberg** [comment]
Aha, found it! https://github.com/joshuakgoldberg/package-build-order

> the repo itself uses another tool such that I can't really use what's built-in.

It should be inferable from the order of dependencies in `package.json` files. As in, doing a tree sort on them.

**Comment by jakebailey** [comment]
Sure, that's what our current thing does, actually, it just also finds the dummy package and tries to install it.

**Comment by JamesHenry** [comment]
I would say that we can ship this fix for now and revisit within a month or so, because we'll be transitioning over to project references first in the Nx tsc setup anyway, so hopefully this becomes a non-issue.

As Josh mentioned, you could add `--skip-nx-cache` to the build command to make sure that you are always running things from scratch

**Comment by jakebailey** [comment]
I can merge this, it'll just have the problem where changes to TS's API affect the build and therefore not actually check anything except `typescript-estree`, which seems a bit useless. I guess it's better than nothing, which is what we have now.

Obviously it's interesting to see when typescript-eslint breaks due to TS API changes, but I doubt that would really inform much given we have to change the AST sometimes and typescript-eslint is only fixed once stable is released. So it's less than nice for AST changes to mean we stop checking any other code in the repo.

**Comment by bradzacher** [comment]
You could do a build with the current version of TS to populate the `dist` and then a second typecheck pass with the linked version of TS.

IIRC the typecheck task doesn't bail after the first failure. Also the typecheck task is more comprehensive as it also covers tests.

Ultimately because TS is something we consume - it won't technically change the build output (aside from ofc you guys changing TS emit output) - which means that the typecheck pass by itself is more interesting than ensuring that the dep graph can consume emitted build files.

**Comment by jakebailey** [comment]
I'll have to try that out; my experience seemed to be that pointing to the linked dep caused the postinstall scripts to run again, so it didn't seem like there was a way out... But I can just drop the postinstall script and update the dep at the same time (which I should have thought of before!)

**Comment by bradzacher** [comment]
Yeah yarn will rerun the postinstall automatically.

If you want you can set `SKIP_POSTINSTALL_BUILD =true` for that link and it'll bypass the build step during postinstall.

**Comment by jakebailey** [comment]
Yarn takes ages to install typescript when it's not one of the ones it knows about, probably due to the patching that can't be opted out of. It still fails to typecheck typescript-estree because the linked typescript is imported and differs from the generated code, but it still seems to check the other ones, at least.

But, opening in the editor, I suspect that it's only typechecking because `TSNode` is `any` due to it referencing the two AST nodes we recently removed for 5.5 (the weird unparsed code ones), which have not been patched back in by the estree package.

**Comment by jakebailey** [comment]
Yarn before...

```
real	1m3.473s
user	1m48.495s
sys	0m15.803s
```

Yarn with resolutions...

```
real	2m19.805s
user	2m11.788s
sys	0m32.465s
```

**Comment by bradzacher** [comment]
It would actually be interesting to run the lint task as well then. We use the `no-unsafe-*` suite of rules so if anything does "fall to `any`" then the lint run should pick it up as an extra layer of checks.

Also a nice check for "runtime validation" of the linked version as it'll actually exercise the code.

**Comment by jakebailey** [comment]
Unfortunately the infrastructure is specific to parsing TypeScript's error messages, not eslint's output, so that wouldn't be possible in the short term.

**Pull request merged**
