### PR TITLE
Allow user tests to specify branch

### PR DESCRIPTION
**Pull request by sandersn**
Update users tests per microsoft/TypeScript#48128

### CODE REVIEW

**Comment by sandersn** [comment]
@weswigham you might be interested in this. The test updates mirror the ones from #48128, and we should eventually shut those down, I think.

Separately, the selection of test projects is 5 years old, and could use some updating as well.

**Comment by sandersn** [comment]
Well, the tests failed about as well as can be expected. I'm going to merge it and try it with an existing test TS PR.

**Comment by sandersn** [comment]
Yep, seems fine.

**Comment by weswigham** [comment]
Re: tests in TS itself. This repo only tracks changes between main and a PR, meanwhile the TS repo tests track changes in `main` itself (after all, we don't run this in every PR). Different purposes, they just happen to use the same suite.

**Pull request merged**
